#!/bin/sh

DESTINATION=$1

git clone -b master git@bitbucket.org:robinrob/ruby-app.git $DESTINATION

cd $DESTINATION
git submodule init
git submodule update

rm Rakefile
ln -s robins-rakefile/Rakefile ./