#!/bin/zsh

IFS="
"

#Black       0;30     Dark Gray     1;30
#Blue        0;34     Light Blue    1;34
#Green       0;32     Light Green   1;32
#Cyan        0;36     Light Cyan    1;36
#Red         0;31     Light Red     1;31
#Purple      0;35     Light Purple  1;35
#Brown       0;33     Yellow        1;33
#Light Gray  0;37     White         1;37

green=$(echo -e "\033[0;32m")
red=$(echo -e "\033[0;31m")
yellow=$(echo -e "\033[0;33m")
blue=$(echo -e "\033[0;34m")
green=$(echo -e "\033[0;32m")
pink=$(echo -e "\033[0;35m")
black=$(echo -e "\033[0;30m")
end=$(echo -e "\033[0m")


write()
{
  echo -e ${1}$2${end}
}

write $pink "Phoenix!"

write $blue "Career options"

write $green "Service to order code"

write $yellow "Alumina Lic Stories"

